FROM golang:1.19-buster as agentbuild
WORKDIR /go/src/github.com/VerizonMedia/kubectl-flame
#added
RUN CGO_ENABLED=0 go install github.com/go-delve/delve/cmd/dlv@latest
ADD . /go/src/github.com/VerizonMedia/kubectl-flame
RUN go get -d -v ./...
#added
RUN cd agent && go build -o /go/bin/agent

# FROM openjdk:8 as asyncprofiler
# #RUN echo deb http://deb.debian.org/debian stretch-backports main > /etc/apt/sources.list.d/stretch-backports.list && \
# #    apt-get update && \
# RUN apt-get update && apt-get -y install build-essential
# RUN git clone https://github.com/edeNFed/async-profiler.git
# RUN cd async-profiler && make

FROM bitnami/minideb as asyncprofiler
RUN install_packages curl tar ca-certificates
# RUN echo deb http://deb.debian.org/debian stretch-backports main > /etc/apt/sources.list.d/stretch-backports.list && \
#    apt-get update && apt-get -y install curl tar
RUN curl -o async-profiler-2.9-linux-x64.tar.gz -L \
    https://github.com/jvm-profiling-tools/async-profiler/releases/download/v2.9/async-profiler-2.9-linux-x64.tar.gz
RUN tar -xvf async-profiler-2.9-linux-x64.tar.gz && mv async-profiler-2.9-linux-x64 async-profiler

FROM bitnami/minideb:stretch
#RUN mkdir -p /app/async-profiler/build
WORKDIR /app
COPY --from=agentbuild /go/bin/agent /app
#added
COPY --from=agentbuild /go/bin/dlv /app
COPY --from=asyncprofiler /async-profiler /app/async-profiler
#COPY --from=asyncprofiler /async-profiler/build /app/async-profiler/build
#COPY --from=asyncprofiler /async-profiler/profiler.sh /app/async-profiler
CMD [ "/app/agent" ]